CREATE TABLE users(
 id BIGSERIAL NOT NULL PRIMARY KEY,
 mobile_id VARCHAR NOT NULL UNIQUE ,
 name VARCHAR NOT NULL
);

CREATE TABLE scores(
 id BIGSERIAL NOT NULL PRIMARY KEY,
 user_id BIGINT REFERENCES users,
 value BIGINT NOT NULL
);