CREATE TABLE users(
 id BIGSERIAL NOT NULL PRIMARY KEY,
 mobileId BIGINT NOT NULL
);

CREATE TABLE scores(
 id BIGSERIAL NOT NULL PRIMARY KEY,
 userId BIGINT REFERENCES users,
 value BIGINT NOT NULL
);